# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.modify_invoice_body import ModifyInvoiceBody  # noqa: E501
from ods_client.rest import ApiException

from pprint import pprint


class TestModifyInvoiceBody(unittest.TestCase):
    """ModifyInvoiceBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifyInvoiceBody(self):
        """Test ModifyInvoiceBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.modify_invoice_body.ModifyInvoiceBody()  # noqa: E501
        # pass

        api_instance = ods_client.HPPBindingApi()
        body = ods_client.ModifyInvoiceBody() # ModifyInvoiceBody | 

        try:
            # ModifyInvoice
            api_response = api_instance.modify_invoice(body)
            pprint(api_response)
        except ApiException as e:
            print("Exception when calling HPPBindingApi->modify_invoice: %s\n" % e)
            assert(False)

if __name__ == '__main__':
    unittest.main()
