# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.change_contact_information import ChangeContactInformation  # noqa: E501
from swagger_client.rest import ApiException

from pprint import pprint


class TestChangeContactInformation(unittest.TestCase):
    """ChangeContactInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeContactInformation(self):
        """Test ChangeContactInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.change_contact_information.ChangeContactInformation()  # noqa: E501
        # pass

        api_instance = swagger_client.HPPBindingApi()
        body = swagger_client.ChangeContactInformation() # ChangeContactInformation | 

        try:
            # InsertPayment
            api_response = api_instance.change_contact_information(body)
            pprint(api_response)
        except ApiException as e:
            print("Exception when calling HPPBindingApi->change_contact_information: %s\n" % e)
            assert(False)

if __name__ == '__main__':
    unittest.main()
