# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.modify_hotel_bank_account_info import ModifyHotelBankAccountInfo  # noqa: E501
from ods_client.rest import ApiException

from pprint import pprint


class TestModifyHotelBankAccountInfo(unittest.TestCase):
    """ModifyHotelBankAccountInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifyHotelBankAccountInfo(self):
        """Test ModifyHotelBankAccountInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.modify_hotel_bank_account_info.ModifyHotelBankAccountInfo()  # noqa: E501

        api_instance = ods_client.HPPBindingApi()

        Q28HotelBankAccountInfo = ods_client.Q28HotelBankAccountInfo(
            customer_no = "customer_no",
            state = "state",
            iban = "iban",
            bic = "bic",
            account_owner = "account_owner",
            mandate_id = "mandate_id"
        )

        Q28HotelBankAccountInfoList = ods_client.Q28HotelBankAccountInfoList([Q28HotelBankAccountInfo])

        TnsModifyHotelBankAccountInfo = ods_client.TnsModifyHotelBankAccountInfo(Q28HotelBankAccountInfoList)

        body = ods_client.ModifyHotelBankAccountInfo(TnsModifyHotelBankAccountInfo)

        try:
            # ModifyHotelCreditCardInfo
            api_response = api_instance.modify_hotel_bank_account_info(body)
        except ApiException as e:
            print("Exception when calling HPPBindingApi->modify_hotel_bank_account_info: %s\n" % e)
            assert(False)        

if __name__ == '__main__':
    unittest.main()
