# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.q8_documents import Q8Documents  # noqa: E501
from ods_client.rest import ApiException


class TestQ8Documents(unittest.TestCase):
    """Q8Documents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQ8Documents(self):
        """Test Q8Documents"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.q8_documents.Q8Documents()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
