# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.all_of_change_contact_information_change_contact_information import AllOfChangeContactInformationChangeContactInformation  # noqa: E501
from ods_client.rest import ApiException


class TestAllOfChangeContactInformationChangeContactInformation(unittest.TestCase):
    """AllOfChangeContactInformationChangeContactInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfChangeContactInformationChangeContactInformation(self):
        """Test AllOfChangeContactInformationChangeContactInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_change_contact_information_change_contact_information.AllOfChangeContactInformationChangeContactInformation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
