# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.q18_positions import Q18Positions  # noqa: E501
from ods_client.rest import ApiException


class TestQ18Positions(unittest.TestCase):
    """Q18Positions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQ18Positions(self):
        """Test Q18Positions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.q18_positions.Q18Positions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
