# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.tns_change_contact_information import TnsChangeContactInformation  # noqa: E501
from ods_client.rest import ApiException


class TestTnsChangeContactInformation(unittest.TestCase):
    """TnsChangeContactInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTnsChangeContactInformation(self):
        """Test TnsChangeContactInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tns_change_contact_information.TnsChangeContactInformation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
