# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.api.hpp_binding_api import HPPBindingApi  # noqa: E501
from ods_client.rest import ApiException


class TestHPPBindingApi(unittest.TestCase):
    """HPPBindingApi unit test stubs"""

    def setUp(self):
        self.api = HPPBindingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_change_contact_information(self):
        """Test case for change_contact_information

        ChangeContactInformation  # noqa: E501
        """
        pass

    def test_change_customer_address(self):
        """Test case for change_customer_address

        ChangeCustomerAddress  # noqa: E501
        """
        pass

    def test_change_customer_address_v2(self):
        """Test case for change_customer_address_v2

        ChangeCustomerAddressV2  # noqa: E501
        """
        pass

    def test_change_invoice_address(self):
        """Test case for change_invoice_address

        ChangeInvoiceAddress  # noqa: E501
        """
        pass

    def test_confirm_invoice(self):
        """Test case for confirm_invoice

        ConfirmInvoice  # noqa: E501
        """
        pass

    def test_insert_payment(self):
        """Test case for insert_payment

        InsertPayment  # noqa: E501
        """
        pass

    def test_insert_payment_v2(self):
        """Test case for insert_payment_v2

        InsertPaymentV2  # noqa: E501
        """
        pass

    def test_insert_payment_v3(self):
        """Test case for insert_payment_v3

        InsertPaymentV3  # noqa: E501
        """
        pass

    def test_modify_hotel_bank_account_info(self):
        """Test case for modify_hotel_bank_account_info

        ModifyHotelBankAccountInfo  # noqa: E501
        """
        pass

    def test_modify_hotel_credit_card_info(self):
        """Test case for modify_hotel_credit_card_info

        ModifyHotelCreditCardInfo  # noqa: E501
        """
        pass

    def test_modify_invoice(self):
        """Test case for modify_invoice

        ModifyInvoice  # noqa: E501
        """
        pass

    def test_modify_invoice_v2(self):
        """Test case for modify_invoice_v2

        ModifyInvoiceV2  # noqa: E501
        """
        pass

    def test_modify_invoice_v3(self):
        """Test case for modify_invoice_v3

        ModifyInvoiceV3  # noqa: E501
        """
        pass

    def test_modify_invoice_v4(self):
        """Test case for modify_invoice_v4

        ModifyInvoiceV4  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
