# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.q2_invoice import Q2Invoice  # noqa: E501
from ods_client.rest import ApiException


class TestQ2Invoice(unittest.TestCase):
    """Q2Invoice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQ2Invoice(self):
        """Test Q2Invoice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.q2_invoice.Q2Invoice()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
