# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.modify_hotel_credit_card_info import ModifyHotelCreditCardInfo  # noqa: E501
from ods_client.rest import ApiException

from pprint import pprint


class TestModifyHotelCreditCardInfo(unittest.TestCase):
    """ModifyHotelCreditCardInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifyHotelCreditCardInfo(self):
        """Test ModifyHotelCreditCardInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.modify_hotel_credit_card_info.ModifyHotelCreditCardInfo()  # noqa: E501
        # pass

        api_instance = ods_client.HPPBindingApi()

        q26_hotelcreditcardinfo = ods_client.Q26HotelCreditCardInfo(
            customer_no = "customer_no",
            pcn = 0,
            expiry = "expiry",
            company = "company",
            authorization_date = "authorization_date",
            state = [
                    "state"
                ],
            scheme_reference_id = "scheme_reference_id"
        )

        hotelcreditcardinfo_list = []
        hotelcreditcardinfo_list.append(q26_hotelcreditcardinfo)

        q26_hotelcreditcardinfolist = ods_client.Q26HotelCreditCardInfoList(hotelcreditcardinfo_list)
        tns_modifyhotelcreditcardinfo = ods_client.TnsModifyHotelCreditCardInfo(q26_hotelcreditcardinfolist)
        body = ods_client.ModifyHotelCreditCardInfoBody(tns_modifyhotelcreditcardinfo) # ModifyHotelCreditCardInfo |

        try:
            # ModifyHotelCreditCardInfo
            api_response = api_instance.modify_hotel_credit_card_info(body)
        except ApiException as e:
            print("Exception when calling HPPBindingApi->modify_hotel_credit_card_info: %s\n" % e)
            assert(False)

if __name__ == '__main__':
    unittest.main()
