# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.change_invoice_address import ChangeInvoiceAddress  # noqa: E501
from ods_client.rest import ApiException

class TestChangeInvoiceAddress(unittest.TestCase):
    """ChangeInvoiceAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeInvoiceAddress(self):
        """Test ChangeInvoiceAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.change_invoice_address.ChangeInvoiceAddress()  # noqa: E501
        # pass

        api_instance = ods_client.HPPBindingApi()

        q2_invoice = ods_client.Q2Invoice(
            invoice_no = "string",
            name = "string",
            name2 = "string",
            address = "string",
            address2 = "string",
            city = "string",
            post_code = "string"
        )

        invoice_list = []
        invoice_list.append(q2_invoice)

        q2_invoices = ods_client.Q2Invoices(invoice_list)


        tns_changeinvoiceaddress = ods_client.TnsChangeInvoiceAddress(q2_invoices)
        body = ods_client.ChangeInvoiceAddress(tns_changeinvoiceaddress) # ChangeInvoiceAddress | 

        # body.to_dict()

        try:
            # InsertPayment
            api_response = api_instance.change_invoice_address(body)
        except ApiException as e:
            print("Exception when calling HPPBindingApi->change_invoice_address: %s\n" % e)
            assert(False)

if __name__ == '__main__':
    unittest.main()
