# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.modify_invoice_v2 import ModifyInvoiceV2  # noqa: E501
from swagger_client.rest import ApiException

from pprint import pprint

class TestModifyInvoiceV2(unittest.TestCase):
    """ModifyInvoiceV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifyInvoiceV2(self):
        """Test ModifyInvoiceV2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.modify_invoice_v2.ModifyInvoiceV2()  # noqa: E501
        pass

        api_instance = swagger_client.HPPBindingApi()
        body = swagger_client.ModifyInvoiceV2Body() # ModifyInvoiceV2Body | 

        try:
            # ModifyInvoiceV2
            api_response = api_instance.modify_invoice_v2(body)
            pprint(api_response)
        except ApiException as e:
            print("Exception when calling HPPBindingApi->modify_invoice_v2: %s\n" % e)
            assert(False)

if __name__ == '__main__':
    unittest.main()
