# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.all_of_modify_invoice_v4_modify_invoice_v4 import AllOfModifyInvoiceV4ModifyInvoiceV4  # noqa: E501
from ods_client.rest import ApiException


class TestAllOfModifyInvoiceV4ModifyInvoiceV4(unittest.TestCase):
    """AllOfModifyInvoiceV4ModifyInvoiceV4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfModifyInvoiceV4ModifyInvoiceV4(self):
        """Test AllOfModifyInvoiceV4ModifyInvoiceV4"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_modify_invoice_v4_modify_invoice_v4.AllOfModifyInvoiceV4ModifyInvoiceV4()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
