# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.change_contact_information import ChangeContactInformation  # noqa: E501
from ods_client.rest import ApiException

class TestChangeContactInformation(unittest.TestCase):
    """ChangeContactInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeContactInformation(self):
        """Test ChangeContactInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.change_contact_information.ChangeContactInformation()  # noqa: E501

        api_instance = ods_client.HPPBindingApi()

        q6contact = ods_client.Q6Contact(
            contact_no = "contact_no",
            first_name = "first_name",
            middle_name = "middle_name",
            surname = "surname",
            e_mail = "e_mail",
            phone_no = "phone_no",
            fax_no = "fax_no"
        )

        contact_list = []
        contact_list.append(q6contact)

        q6contactlist = ods_client.Q6ContactList(contact_list)

        tnschangecontactinformation = ods_client.TnsChangeContactInformation(q6contactlist)

        body = ods_client.ChangeContactInformation(tnschangecontactinformation) # ChangeContactInformation | 

        try:
            # InsertPayment
            api_response = api_instance.change_contact_information(body)
        except ApiException as e:
            print("Exception when calling HPPBindingApi->change_contact_information: %s\n" % e)
            assert(False)

if __name__ == '__main__':
    unittest.main()
