# coding: utf-8

"""
    OIP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import oip_client
from oip_client.api.default_api import DefaultApi  # noqa: E501
from oip_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accountingdocuments_document_id_put(self):
        """Test case for accountingdocuments_document_id_put

        Update Accounting Document  # noqa: E501
        """
        pass

    def test_bank_account_info_post(self):
        """Test case for bank_account_info_post

        Submit Bank Account Information  # noqa: E501
        """
        pass

    def test_booking_source_post(self):
        """Test case for booking_source_post

        Create Booking Source  # noqa: E501
        """
        pass

    def test_countries_post(self):
        """Test case for countries_post

        Create Country  # noqa: E501
        """
        pass

    def test_hotels_post(self):
        """Test case for hotels_post

        Create Hotel  # noqa: E501
        """
        pass

    def test_payment_methods_post(self):
        """Test case for payment_methods_post

        Create Payment Method  # noqa: E501
        """
        pass

    def test_salesperson_post(self):
        """Test case for salesperson_post

        Create Salesperson  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
