swagger: '2.0'
info:
  description: If an opportunity was marked as "transfer to BC" then a contract and contract line is created in BC. Allong with all line items defined in SalesForce
  version: 1.0.0.4
  title: adding or modifing a contract
  # put the contact info for your development or API team
  contact:
    email: thomas@marquardt-informatik.koeln

# tags are used for organizing operations
tags:
- name: developers
  description: Operations available to regular developers

paths:
  /lscontracts:
    post:
      tags:
      - developers
      summary: adds an opportunity as contract line into BC
      operationId: addOpportunity
      description: Adds an contract line to the system
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: opportunity
        description: Opportunity to add
        schema:
          $ref: '#/definitions/Opportunities'
      responses:
        200:
          description: Created Contact
          schema:
            $ref: '#/definitions/OpportunitiesResult'
definitions:
  Opportunities:
    type: object
    required:
    - opportunityId
    - acceptanceDate
    - contractStart
    - contractEnd
    properties:
      opportunityId:
        type: string
        example: 0012000000ZRUqYAAX
      parentOpportunityId:
        type: string
        example: 001D000001gBWCAIA4
      oppLegalEntity:
        type: string
        enum: [Learnship Networks Gmbh,GlobalEnglish Corporation, ]
        example: Learnship Networks Gmbh
        description: List of legal entities must be synchroniced with BC
      accountId:
        type: string
        example: 0012000000ZRUqYBBX
        description: Id of the SalesForce Account in Salesforce
      invoiceAccountId:
        type: string
        example: 0012000000ZRUqYBBX
        description: Id of the SalesForce Account in Salesforce used for invoicing
      invoiceContactId:
        type: string
        example: 0012000000ZRUqYBBX
        description: Id of the SalesForce Contact in Salesforce used for invoicing
      stage:
        type: string
        enum: [1-....,6-Closed Won,7-Closed Lost]
        example: 6 - Close (Won)
      billingMethod:
        type: string
        enum: [postpaid regular,prepaid regular,prepaid billing plan,prepaid with events]
        example: postpaid regular
        description: list of billing methods comes from BC
      customerLegalName:
        type: string
      language:
        type: string
        enum: [EN, FR, DE, JP, CN, PT, ESP]
        example: DE
        description: Language 2-letter ISO-Code
      currency:
        type: string
        example: EUR
        description: 3-letter ISO-Code for the currency
      paymentTerms:
        type: string
        enum: [immediately,30,45,60,90]
        example: 30
      billToAccountId:
        type: string
        example: 0012000000ZRUqYAAX
      billToCountry:
        type: string
        example: DE
      billToStreet:
        type: string
        example: Carl-Schurz-Straße 1
      billToPostcode:
        type: string
        example: 41460 
      billToCity:
        type: string
        example: Neuss
      billToState:
        type: string
        example: NRW
      billToContactName:
        type: string
        example: Anja Dondrup
      billToContactPhone:
        type: string
        example: 123-456-3333
      billToContacteMail:
        type: string
        example: adondrup@mmm.com
      sellToAccountId:
        type: string
        example: 0012000000ZRUqYAAX
      sellToCountry:
        type: string
        example: DE
        description: SalesForce Label -> Different Billing Country
      sellToStreet:
        type: string
        example: Carl-Schurz-Straße 1
      sellToPostcode:
        type: string
        example: 41460 
      sellToCity:
        type: string
        example: Neuss
      sellToState:
        type: string
        example: NRW
      sellToContactName:
        type: string
        example: Anja Dondrup
      sellToContactPhone:
        type: string
        example: 123-456-3333
      sellToContacteMail:
        type: string
        example: adondrup@mmm.com
      acceptanceDate:
        type: string
        format: date
        description: the date as contract was signed
      contractStart:
        type: string
        format: date
        description: the starting date of the contract
      contractEnd:
        type: string
        format: date
        description: the ending date of the contract
      budget:
        type: number
        format: double
        example: 1000.00
        minimum: 0
        description: If a lumpsum value should limit all costs agains the customer
      budgetCurrency:
        type: string
        example: EUR
        description: 3-letter ISO-Code for the currency
      budgetType:
        type: string
        enum: [Flexible Budget,Kontingent,Bundel]
      sendingProfile:
        type: string
        example: STANDARD
        description: List of sending profiles is provided by BC. The sending profile controls the delivery and the document creation.
      purchaseOrder:
        type: string
        example: PO1234
        description: Purchase order of customer
      ordererName:
        type: string
        example: Max Mustermann
        description: This person from the customer signed the contract
      ordererEMail:
        type: string
        example: Max.Mustermann@customer.com
        description: EMail address of the orderer
      additionalText:
        type: string
        example: This Text is for all documents
        description: This Text is displayed on documents if the sending profile was configured to use this
      costCenter:
        type: string
        example: K1234
        description: the customer costcenter related to this opportunity
      installmentsNeeded:
        type: string
        format: boolean
        example: yes
      installments:
        type: number
        format: int32
        example: 1
      lineItems:
        type: array
        items:
          $ref: '#/definitions/LineItems'
      invoiceItems:
        type: array
        items:
          $ref: '#/definitions/InvoiceItems'
  OpportunitiesResult:
    properties:
      '@odata.context':
        type: string
        example: https://api.businesscentral.dynamics.com/v2.0/cb074161-d878-4784-a259-30495e796802/Sandbox/api/destinationSolutions/bde/v1.0/$metadata#companies(5fc4a8c4-89d1-ea11-bb6c-000d3a2beb23)/bookings/$entity
      '@odata.etag':
        type: string
        example: W/\"JzQ0O1NXRXlNZ0c0SndFS2tYcmFEMm5jbHVZeEVGNWNnQlI1RklkcG0xcGhkaUU9MTswMDsn\"
      bcContractId:
        type: string
        example: CO000001
      opportunityId:
        type: string
        example: 0012000000ZRUqYAAX
      parentOpportunityId:
        type: string
        example: 001D000001gBWCAIA4
      oppLegalEntity:
        type: string
        enum: [Learnship Networks Gmbh,GlobalEnglish Corporation, ]
        example: Learnship Networks Gmbh
        description: List of legal entities must be synchroniced with BC
      accountId:
        type: string
        example: 0012000000ZRUqYBBX
        description: Id of the SalesForce Account in Salesforce
      invoiceAccountId:
        type: string
        example: 0012000000ZRUqYBBX
        description: Id of the SalesForce Account in Salesforce used for invoicing
      invoiceContactId:
        type: string
        example: 0012000000ZRUqYBBX
        description: Id of the SalesForce Contact in Salesforce used for invoicing
      stage:
        type: string
        enum: [1-....,6-Closed Won,7-Closed Lost]
        example: 6 - Close (Won)
      billingMethod:
        type: string
        enum: [postpaid regular,prepaid regular,prepaid billing plan,prepaid with events]
        example: postpaid regular
        description: list of billing methods comes from BC
      customerLegalName:
        type: string
      language:
        type: string
        enum: [EN, FR, DE, JP, CN, PT, ESP]
        example: DE
        description: Language 2-letter ISO-Code
      currency:
        type: string
        example: EUR
        description: 3-letter ISO-Code for the currency
      paymentTerms:
        type: string
        enum: [immediately,30,45,60,90]
        example: 30
      billToAccountId:
        type: string
        example: 0012000000ZRUqYAAX
      billToCountry:
        type: string
        example: DE
      billToStreet:
        type: string
        example: Carl-Schurz-Straße 1
      billToPostcode:
        type: string
        example: 41460 
      billToCity:
        type: string
        example: Neuss
      billToState:
        type: string
        example: NRW
      billToContactName:
        type: string
        example: Anja Dondrup
      billToContactPhone:
        type: string
        example: 123-456-3333
      billToContacteMail:
        type: string
        example: adondrup@mmm.com
      sellToAccountId:
        type: string
        example: 0012000000ZRUqYAAX
      sellToCountry:
        type: string
        example: DE
        description: SalesForce Label -> Different Billing Country
      sellToStreet:
        type: string
        example: Carl-Schurz-Straße 1
      sellToPostcode:
        type: string
        example: 41460 
      sellToCity:
        type: string
        example: Neuss
      sellToState:
        type: string
        example: NRW
      sellToContactName:
        type: string
        example: Anja Dondrup
      sellToContactPhone:
        type: string
        example: 123-456-3333
      sellToContacteMail:
        type: string
        example: adondrup@mmm.com
      acceptanceDate:
        type: string
        format: date
        description: the date as contract was signed
      contractStart:
        type: string
        format: date
        description: the starting date of the contract
      contractEnd:
        type: string
        format: date
        description: the ending date of the contract
      budget:
        type: number
        format: double
        example: 1000.00
        minimum: 0
        description: If a lumpsum value should limit all costs agains the customer
      budgetCurrency:
        type: string
        example: EUR
        description: 3-letter ISO-Code for the currency
      budgetType:
        type: string
        enum: [Flexible Budget,Kontingent,Bundel]
      sendingProfile:
        type: string
        example: STANDARD
        description: List of sending profiles is provided by BC. The sending profile controls the delivery and the document creation.
      purchaseOrder:
        type: string
        example: PO1234
        description: Purchase order of customer
      ordererName:
        type: string
        example: Max Mustermann
        description: This person from the customer signed the contract
      ordererEMail:
        type: string
        example: Max.Mustermann@customer.com
        description: EMail address of the orderer
      additionalText:
        type: string
        example: This Text is for all documents
        description: This Text is displayed on documents if the sending profile was configured to use this
      costCenter:
        type: string
        example: K1234
        description: the customer costcenter related to this opportunity
      installmentsNeeded:
        type: string
        format: boolean
        example: yes
      installments:
        type: number
        format: int32
        example: 1
      lineItems:
        type: array
        items:
          $ref: '#/definitions/LineItemsResult'
      invoiceItems:
        type: array
        items:
          $ref: '#/definitions/InvoiceItemsResult'
  LineItems:
    type: object
    required:
      - lineItemId
      - productId
      - quantity
    properties:
      lineItemId: 
        type: string
        example: 00k7Z000008comrQAA
      productId: 
        type: string
        example: 01t2p00000CPNfZAAX
      quantity:
        type: number
        format: double
        example: 20.0
        minimum: 1
      unitSalesPrice:
        type: number
        format: double
        example: 190.00
        description: This is the Price which will be invoiced for each product. In this Example the total price will be 20 * 190 = 3,800
      currency:
        type: string
        example: EUR
        description: 3-letter ISO-Code for the currency
      serviceActivationDate:
        type: string
        format: date
        example: 2022-11-14
      serviceExpirationDate:
        type: string
        format: date
        example: 2024-04-07
      enrollmentEndDate:
        type: string
        format: date
      serviceFee:
        type: number
        format: double
        example: 108
        description: Fee to setup a Course
  LineItemsResult:
    type: object
    required:
      - contractPriceId
    properties:
      '@odata.etag':
        type: string
        example: W/\"JzQ0O0xiaXpkTjU4dXQyNmxmcDF5UmNPdGZYRlE0b29sL25QTGp4S2FWVDhuR2c9MTswMDsn\"
      contractPriceId:
        type: string
        format: uuid
        example: a290f1ee-6c54-6565-90e6-d701748f0851
        description: unique Id of the contract price Id
      lineItemId: 
        type: string
        example: 00k7Z000008comrQAA
      productId: 
        type: string
        example: 01t2p00000CPNfZAAX
      quantity:
        type: number
        format: double
        example: 20.0
        minimum: 1
      unitSalesPrice:
        type: number
        format: double
        example: 190.00
        description: This is the Price which will be invoiced for each product. In this Example the total price will be 20 * 190 = 3,800
      currency:
        type: string
        example: EUR
        description: 3-letter ISO-Code for the currency
      serviceActivationDate:
        type: string
        format: date
        example: 2022-11-14
      serviceExpirationDate:
        type: string
        format: date
        example: 2024-04-07
      enrollmentEndDate:
        type: string
        format: date
  InvoiceItems:
    type: object
    required:
      - multipleInvoiceId
      - opportunityId
      - lineItemId
    properties:
      multipleInvoiceId:
        type: string
        example: a3W7Z000000lKOwUAM
        description: Multiple_Invoice__c in Multiple Invoice Product
      opportunityId:
        type: string
        example: 0012000000ZRUqYAAX
        description: This is the Opportunity__c in Multiple Invoice Product
      lineItemId: 
        type: string
        example: 00k7Z000008comrQAA
        description: This is the Opportunity_Product__c in Multiple Invoice Product
      invoiceAccountId:
        type: string
        example: 0012000000ZRUqYBBX
        description: Invoice_Account__c in Multiple Invoice
      invoiceContactId:
        type: string
        example: 0012000000ZRUqYBBX
        description: Invoice_Contact__c in Multiple Invoice 
      quantity:
        type: number
        format: double
        example: 20.0
        minimum: 1
        description: Units__c in Multiple Invoice Product
      unitSalesPrice:
        type: number
        format: double
        example: 190.00
        description: Price_per_session__c in Multiple Invoice Product
      currency:
        type: string
        example: EUR
        description: CurrencyIsoCode in Multiple Invoice Product
      serviceActivationDate:
        type: string
        format: date
        example: 2022-11-14
        description: Service_Activation_Date__c in Multiple Invoice Product
      serviceExpirationDate:
        type: string
        format: date
        example: 2024-04-07
        description: Service_Expiration_Date__c in Multiple Invoice Product
      serviceFee:
        type: number
        format: double
        example: 108
        description: Additional_Invoice_Fee__c in Multiple Invoice
      purchaseOrder:
        type: string
        example: PO1234
        description: PO_Number_if_required__c in Multiple Invoice
      poRequired:
        type: string
        example: true
        description: PO_Number_if_required__c in Multiple Invoice
  InvoiceItemsResult:
    type: object
    required:
      - multipleInvoiceId
      - opportunityId
      - lineItemId
    properties:
      '@odata.etag':
        type: string
        example: W/\"JzQ0O0xiaXpkTjU4dXQyNmxmcDF5UmNPdGZYRlE0b29sL25QTGp4S2FWVDhuR2c9MTswMDsn\"
      multipleInvoiceId:
        type: string
        example: a3W7Z000000lKOwUAM
        description: Multiple_Invoice__c in Multiple Invoice Product
      opportunityId:
        type: string
        example: 0012000000ZRUqYAAX
        description: This is the Opportunity__c in Multiple Invoice Product
      lineItemId: 
        type: string
        example: 00k7Z000008comrQAA
        description: This is the Opportunity_Product__c in Multiple Invoice Product
      invoiceAccountId:
        type: string
        example: 0012000000ZRUqYBBX
        description: Invoice_Account__c in Multiple Invoice
      invoiceContactId:
        type: string
        example: 0012000000ZRUqYBBX
        description: Invoice_Contact__c in Multiple Invoice 
      quantity:
        type: number
        format: double
        example: 20.0
        minimum: 1
        description: Units__c in Multiple Invoice Product
      unitSalesPrice:
        type: number
        format: double
        example: 190.00
        description: Price_per_session__c in Multiple Invoice Product
      currency:
        type: string
        example: EUR
        description: CurrencyIsoCode in Multiple Invoice Product
      serviceActivationDate:
        type: string
        format: date
        example: 2022-11-14
        description: Service_Activation_Date__c in Multiple Invoice Product
      serviceExpirationDate:
        type: string
        format: date
        example: 2024-04-07
        description: Service_Expiration_Date__c in Multiple Invoice Product
      serviceFee:
        type: number
        format: double
        example: 108
        description: Additional_Invoice_Fee__c in Multiple Invoice
      purchaseOrder:
        type: string
        example: PO1234
        description: PO_Number_if_required__c in Multiple Invoice
      poRequired:
        type: string
        example: true
        description: PO_Number_if_required__c in Multiple Invoice
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Marquardt-Informatik/contracts/1.0.0.4
schemes:
 - https
 