swagger: '2.0'
info:
  description: Create or update Product
  version: 1.0.0
  title: Product catalog from SalesForce
  # put the contact info for your development or API team
  contact:
    email: thomas@marquardt-informatik.koeln

# tags are used for organizing operations
tags:
- name: developers
  description: Operations available to regular developers

paths:
  /products:
    post:
      tags:
      - developers
      summary: adds a course record into BC
      operationId: createProduct
      description: adds or modifies a Product in BC
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: products
        description: Products to add
        schema:
          $ref: '#/definitions/Products'
      responses:
        200:
          description: Created Course
          schema:
            $ref: '#/definitions/ProductsResult'
definitions:
  Products:
    type: object
    required:
    - sfProductId
    properties:
      sfProductId:
        type: string
        example: 01t2p00000DFw0xAAD
      productCode:
        type: string
        example: ELEVATE-LT-ONLINE-P-ENG-17-60-AUT
      currency:
        type: string
        description: 3-letter ISO-Code
        example: USD
      description:
        type: string
        example: For learners who want to practice and improve their written or verbal language skills with a dedicated trainer. Programs are available for individual learners or groups with similar abilities and shared goals
        description: Product description max 4000 characters
      family:
        type: string
        enum: [Baseline,Coach,Elevate,Evolve,Fees,Professional Services,Solo,Sprint]
        example: Elevate
      name:
        type: string
        example: Autodesk Elevate Language Training Online Private English (17 sessions x 60 minutes)
        description: max length 255
      numberOfHours:
        type: string
        enum: [Fixed Price,Hourly,No cost,8,1,11,22,3,20,30,18,36,40,72,20.5,45,5,10,15,25,35,90,57,114,16]
        example: Fixed Price
      numberOfSessions:
        type: string
        example: 17
        description: max length 255
      numberOfSubscribers:
        type: string
        enum: [10 to 20,1 to 19,1 to 5,20 to 50,20 to 150,up to 20,up to 50]
      bwf:
        type: string
        enum: [N/A,Add On,Included]
      category:
        type: string
        enum: [Administrative,Assessments,Blended,Digital,Flexible Deployment,Prepaid Licenses and Fees,Professional Services,Trainer-led]
        example: Trainer-led
      content:
        type: string
        enum: [Business Skills,Change,Coaching,Focus,Language Training,Levels Progress,Power Skills,Relocation]
        example: Language Training
      contentType:
        type: string
        enum: [Culture,Language]
        example: Language
      courseType:
        type: string
        enum: [Group,Private]
        example: Private
      deliveryChannel:
        type: string
        enum: [Online,Onsite]
        example: Online
      elementType:
        type: string
        enum: [One-time,Standard,Package]
        example: Package
      geProductId:
        type: string
        example: 01t4z000007sZcBAAU
      geProductIdRef:
        type: string
        example: 01t4z000007sZcBAAU
      language:
        type: string
        enum: [Arabic,Czech,Dutch,English,Flemish,French,German,Hindi,Hungarian,Indonesian,Italian,Japanese,Korean,Mandarin,Norwegian,Portuguese,Romanian,Russian,Slovak,Spanish,Swedish,Thai,Turkish]
        example: English
      learningMode:
        type: string
        enum: [Blended,Self-paced,Trainer-led]
        example: Trainer-led
      periodOfUse:
        type: string
        enum: [12 Months,17 Weeks,1 Day,45 Days,1 Month,24 Months,3 Months,4 Months,6 Months,8 Months,9 Months,N/A]
        example: N/A
      productDescriptionInvoice:
        type: string
        example: Autodesk Elevate Language Training Online Private English (17 sessions x 60 minutes)
        description: max length 255
      productEntity:
        type: string
        enum: [LS,GE,Learnship]
        example: Learnship
      productLine:
        type: string
        enum: [Solo - Business Language,Sprint - Business Language,Sprint - Business Skills,Coach - Language Coach,Coach - Culture Coach,Elevate - Language Training,Baseline,Elevate - Business Language,Elevate - Business Skills,Evolve - Culture Change,Evolve - Culture Focus,Evolve - Culture Power Skills,Evolve - General,Evolve - Relocation Language Training,Fees,Professional Services]
        example: Elevate - Language Training
      productType:
        type: string
        enum: [Assessment Product,Fees,Professional Services,Training Product]
        example: Training Product
      productVersion:
        type: string
        enum: [Beta,Client Specific,Pilot,Standard,Trial]
        example: Client Specific
      sessionLength:
        type: string
        enum: [30,45,60,90,120,240,480,960]
        example: 60
      trainingType:
        type: string
        enum: [Business Language Coaching,Comprehensive,GE Coach,GE Skills,Intercultural Training,Language Training,Levels Progress,OUP Level,Relocation,Specific Purpose Business Modules]
        example: Language Training
  ProductsResult:
    properties:
      '@odata.context':
        type: string
        example: https://api.businesscentral.dynamics.com/v2.0/cb074161-d878-4784-a259-30495e796802/Sandbox/api/destinationSolutions/bde/v1.0/$metadata#companies(5fc4a8c4-89d1-ea11-bb6c-000d3a2beb23)/bookings/$entity
      '@odata.etag':
        type: string
        example: W/\"JzQ0O1NXRXlNZ0c0SndFS2tYcmFEMm5jbHVZeEVGNWNnQlI1RklkcG0xcGhkaUU9MTswMDsn\"
      sfPproductId:
        type: string
        example: 01t2p00000DFw0xAAD
      productCode:
        type: string
        example: ELEVATE-LT-ONLINE-P-ENG-17-60-AUT
      currency:
        type: string
        description: 3-letter ISO-Code
        example: USD
      description:
        type: string
        example: For learners who want to practice and improve their written or verbal language skills with a dedicated trainer. Programs are available for individual learners or groups with similar abilities and shared goals
        description: Product description max 4000 characters
      family:
        type: string
        enum: [Baseline,Coach,Elevate,Evolve,Fees,Professional Services,Solo,Sprint]
        example: Elevate
      name:
        type: string
        example: Autodesk Elevate Language Training Online Private English (17 sessions x 60 minutes)
        description: max length 255
      numberOfHours:
        type: string
        enum: [Fixed Price,Hourly,No cost,8,1,11,22,3,20,30,18,36,40,72,20.5,45,5,10,15,25,35,90,57,114,16]
        example: Fixed Price
      numberOfSessions:
        type: string
        example: 17
        description: max length 255
      numberOfSubscribers:
        type: string
        enum: [10 to 20,1 to 19,1 to 5,20 to 50,20 to 150,up to 20,up to 50]
      bwf:
        type: string
        enum: [N/A,Add On,Included]
      category:
        type: string
        enum: [Administrative,Assessments,Blended,Digital,Flexible Deployment,Prepaid Licenses and Fees,Professional Services,Trainer-led]
        example: Trainer-led
      content:
        type: string
        enum: [Business Skills,Change,Coaching,Focus,Language Training,Levels Progress,Power Skills,Relocation]
        example: Language Training
      contentType:
        type: string
        enum: [Culture,Language]
        example: Language
      courseType:
        type: string
        enum: [Group,Private]
        example: Private
      deliveryChannel:
        type: string
        enum: [Online,Onsite]
        example: Online
      elementType:
        type: string
        enum: [One-time,Standard,Package]
        example: Package
      geProductId:
        type: string
        example: 01t4z000007sZcBAAU
      geProductIdRef:
        type: string
        example: 01t4z000007sZcBAAU
      language:
        type: string
        enum: [Arabic,Czech,Dutch,English,Flemish,French,German,Hindi,Hungarian,Indonesian,Italian,Japanese,Korean,Mandarin,Norwegian,Portuguese,Romanian,Russian,Slovak,Spanish,Swedish,Thai,Turkish]
        example: English
      learningMode:
        type: string
        enum: [Blended,Self-paced,Trainer-led]
        example: Trainer-led
      periodOfUse:
        type: string
        enum: [12 Months,17 Weeks,1 Day,45 Days,1 Month,24 Months,3 Months,4 Months,6 Months,8 Months,9 Months,N/A]
        example: N/A
      productDescriptionInvoice:
        type: string
        example: Autodesk Elevate Language Training Online Private English (17 sessions x 60 minutes)
        description: max length 255
      productEntity:
        type: string
        enum: [LS,GE,Learnship]
        example: Learnship
      productLine:
        type: string
        enum: [Solo - Business Language,Sprint - Business Language,Sprint - Business Skills,Coach - Language Coach,Coach - Culture Coach,Elevate - Language Training,Baseline,Elevate - Business Language,Elevate - Business Skills,Evolve - Culture Change,Evolve - Culture Focus,Evolve - Culture Power Skills,Evolve - General,Evolve - Relocation Language Training,Fees,Professional Services]
        example: Elevate - Language Training
      productType:
        type: string
        enum: [Assessment Product,Fees,Professional Services,Training Product]
        example: Training Product
      productVersion:
        type: string
        enum: [Beta,Client Specific,Pilot,Standard,Trial]
        example: Client Specific
      sessionLength:
        type: string
        enum: [30,45,60,90,120,240,480,960]
        example: 60
      trainingType:
        type: string
        enum: [Business Language Coaching,Comprehensive,GE Coach,GE Skills,Intercultural Training,Language Training,Levels Progress,OUP Level,Relocation,Specific Purpose Business Modules]
        example: Language Training
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
schemes:
 - https
# Added by API Auto Mocking Plugin
basePath: /Marquardt-Informatik/products/1.0.0
