openapi: 3.0.0
info:
  title: HPP
  contact: {}
  version: 1.0.0.0
servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/Marquardt-Informatik/HPP/1.0.0.0
- url: http://p-nav-as-1-m.int.hrs.com:7047/DynNavHRS/ws/HRS/Codeunit/HPP?WSDL
  variables: {}
paths:
  /InsertPayment:
    post:
      tags:
      - HPP_Binding
      summary: InsertPayment
      operationId: InsertPayment
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/InsertPayment'
              - xml:
                  name: InsertPayment
                  attribute: false
                  wrapped: false
        required: true
      responses:
        '200':
          description: Successfully retrieved the response
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/InsertPayment_Result'
                - xml:
                    name: InsertPayment_Result
                    attribute: false
                    wrapped: false
      deprecated: false
components:
  schemas:

    q8_Document:
      title: q8_Document
      required:
      - DocumentNo
      type: object
      properties:
        DocumentNo:
          type: string
          xml:
            name: DocumentNo
            namespace: urn:microsoft-dynamics-nav/xmlports/x50038
            prefix: q8
            attribute: false
            wrapped: false
      description: ''
      xml:
        name: Document
        namespace: urn:microsoft-dynamics-nav/xmlports/x50038
        prefix: q8
        attribute: false
        wrapped: false
    q8_Documents:
      title: q8_Documents
      required:
      - Document
      type: object
      properties:
        Document:
          type: array
          items:
            $ref: '#/components/schemas/q8_Document'
          description: ''
          xml:
            namespace: urn:microsoft-dynamics-nav/xmlports/x50038
            prefix: q8
            attribute: false
            wrapped: false
      description: ''
      xml:
        name: Documents
        namespace: urn:microsoft-dynamics-nav/xmlports/x50038
        prefix: q8
        attribute: false
        wrapped: false


    q8_PaymentLine:
      title: q8_PaymentLine
      required:
      - PostingDate
      - PaymentMethodCode
      - ExtDocumentNo
      - Documents
      - CurrencyCode
      - RemainingAmount
      - FixFeeAmount
      - VarFeeAmount
      type: object
      properties:
        PostingDate:
          type: string
          xml:
            name: PostingDate
            namespace: urn:microsoft-dynamics-nav/xmlports/x50038
            prefix: q8
            attribute: false
            wrapped: false
        PaymentMethodCode:
          type: string
          xml:
            name: PaymentMethodCode
            namespace: urn:microsoft-dynamics-nav/xmlports/x50038
            prefix: q8
            attribute: false
            wrapped: false
        ExtDocumentNo:
          type: string
          xml:
            name: ExtDocumentNo
            namespace: urn:microsoft-dynamics-nav/xmlports/x50038
            prefix: q8
            attribute: false
            wrapped: false
        Documents:
          allOf:
          - $ref: '#/components/schemas/q8_Documents'
          - xml:
              name: Documents
              namespace: urn:microsoft-dynamics-nav/xmlports/x50038
              prefix: q8
              attribute: false
              wrapped: false
        CurrencyCode:
          type: string
          xml:
            name: CurrencyCode
            namespace: urn:microsoft-dynamics-nav/xmlports/x50038
            prefix: q8
            attribute: false
            wrapped: false
        RemainingAmount:
          type: string
          xml:
            name: RemainingAmount
            namespace: urn:microsoft-dynamics-nav/xmlports/x50038
            prefix: q8
            attribute: false
            wrapped: false
        FixFeeAmount:
          type: string
          xml:
            name: FixFeeAmount
            namespace: urn:microsoft-dynamics-nav/xmlports/x50038
            prefix: q8
            attribute: false
            wrapped: false
        VarFeeAmount:
          type: string
          xml:
            name: VarFeeAmount
            namespace: urn:microsoft-dynamics-nav/xmlports/x50038
            prefix: q8
            attribute: false
            wrapped: false
      description: ''
      xml:
        name: PaymentLine
        namespace: urn:microsoft-dynamics-nav/xmlports/x50038
        prefix: q8
        attribute: false
        wrapped: false
    q8_PaymentLines:
      title: q8_PaymentLines
      required:
      - PaymentLine
      type: object
      properties:
        PaymentLine:
          type: array
          items:
            $ref: '#/components/schemas/q8_PaymentLine'
          description: ''
          xml:
            namespace: urn:microsoft-dynamics-nav/xmlports/x50038
            prefix: q8
            attribute: false
            wrapped: false
      description: ''
      xml:
        name: PaymentLines
        namespace: urn:microsoft-dynamics-nav/xmlports/x50038
        prefix: q8
        attribute: false
        wrapped: false

    tns_InsertPayment:
      title: tns_InsertPayment
      required:
      - insertPayment
      type: object
      properties:
        insertPayment:
          allOf:
          - $ref: '#/components/schemas/q8_PaymentLines'
          - xml:
              name: insertPayment
              namespace: urn:microsoft-dynamics-schemas/codeunit/HPP
              prefix: tns
              attribute: false
              wrapped: false
      description: ''
      xml:
        name: InsertPayment
        namespace: urn:microsoft-dynamics-schemas/codeunit/HPP
        prefix: tns
        attribute: false
        wrapped: false

    tns_InsertPayment_Result:
      title: tns_InsertPayment_Result
      required:
      - insertPayment
      type: object
      properties:
        insertPayment:
          allOf:
          - $ref: '#/components/schemas/q8_PaymentLines'
          - xml:
              name: insertPayment
              namespace: urn:microsoft-dynamics-schemas/codeunit/HPP
              prefix: tns
              attribute: false
              wrapped: false
      description: ''
      xml:
        name: InsertPayment_Result
        namespace: urn:microsoft-dynamics-schemas/codeunit/HPP
        prefix: tns
        attribute: false
        wrapped: false

    InsertPayment:
      title: InsertPayment
      required:
      - InsertPayment
      type: object
      properties:
        InsertPayment:
          allOf:
          - $ref: '#/components/schemas/tns_InsertPayment'
          - {}

    InsertPayment_Result:
      title: InsertPayment_Result
      required:
      - InsertPayment_Result
      type: object
      properties:
        InsertPayment_Result:
          allOf:
          - $ref: '#/components/schemas/tns_InsertPayment_Result'
          - xml:
              name: InsertPayment_Result
              attribute: false
              wrapped: false
      xml:
        name: InsertPayment_Result
        attribute: false
        wrapped: false

tags:
- name: HPP_Binding
  description: ''
  