# coding: utf-8

"""
    OIP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import oip_client
from oip_client.models.accounting_document import AccountingDocument  # noqa: E501
from oip_client.rest import ApiException

from pprint import pprint


class TestAccountingDocument(unittest.TestCase):
    """AccountingDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountingDocument(self):
        """Test AccountingDocument"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.accounting_document.AccountingDocument()  # noqa: E501

        # Configure OAuth2 access token for authorization: oauth2
        configuration = oip_client.Configuration()
        configuration.access_token = 'YOUR_ACCESS_TOKEN'

        api_instance = oip_client.DefaultApi()

        position = oip_client.Position(
            company = "HRS",
            process_number = 162621580,
            reservation_no = 283301172,
            position_no = 1,
            client_guestname1 = "CANSECO AQUINO, ALEJANDRO CLAUDIO",
            client_guestname2 = "string",
            client_company = "VW Cytric_Mexiko",
            room_type = 0,
            number_of_rooms = 1,
            number_of_person = 0,
            breakfast_approval_status = "0",
            arrival_date = "2023-08-15",
            departure_date = "2023-08-15",
            number_of_nights = 2,
            rate_description = "VolkswagenAG",
            rate_type = 21011,
            breakfast_type = 0,
            breakfast_price = 0,
            currency_factor = 18.90034,
            currency_code = "MXN",
            commission_amount = 1500,
            comission_rate = 0,
            room_price = 1500,
            ranking_booster = 0,
            booking_quality = 0,
            booking_code = "string",
            quality_at = "2023-08-15T06:59:55.198Z",
            quality_by_user = "string",
            reservation_source = "81",
            deduction_type = 0,
            calculated_with_function_id = "CalculatedWithFunctionID",
            customer_no = "378128",
            taf_line_amount = 94.5,
            agency_line_amount = 0,
            line_amount = 94.5,
            line_amount_including_vat = 94.5,
            amount_including_vat = 1500,
            total_amount_including_vat = 3000
        )

        body = oip_client.AccountingDocument(
            amount_currency_code = 'MXN',
            company = "string",
            confirmed = False,
            correction_from_document_no = "string",
            customer_no = 378128,
            debitor_currency_rate = 18.90034,
            description = "Rechnung R010876989",
            document_date = "2023-08-15" ,
            document_no = "16846361",
            document_type = "Payment",
            exchange_rate = 1,
            external_document_no = "string",
            fapiao_no = "string" ,
            foreign_currency_code = "MXN",
            has_pdf = False,
            hotel_address_city = "Col. El Coecillo,Leon",
            hotel_address_country_region_code = "102",
            hotel_address_line1 = "Bulevar Adolfo Lopez Mateos 2611",
            hotel_address_line2 = "string" ,
            hotel_address_name = "Radisson Poliforum Plaza Hotel Leon",
            hotel_address_name2 = "string",
            hotel_address_post_code = "37260",
            invoice_address_city = "Col. El Coecillo,Leon",
            invoice_address_contact_no = "string",
            invoice_address_country_region_code = "102",
            invoice_address_customer_no = "378128",
            invoice_address_email = "string",
            invoice_address_line1 = "Bulevar Adolfo Lopez Mateos 2611",
            invoice_address_line2 = "string",
            invoice_address_name = "Radisson Poliforum Plaza Hotel Leon",
            invoice_address_name2 = "string",
            invoice_address_post_code = "37260",
            invoice_exchange_rate = 18.90034,
            ledger_entry_no = 0,
            local_currency_code = "EUR",
            open = True,
            orig_number_of_nights = 4,
            original_amount_gross = 189,
            original_amount_net = 189,
            original_amount_vat = 0,
            original_foreign_amount_gross = 189,
            original_local_amount_gross = 10,
            posting_date = "2023-08-15",
            remaining_amount_gross = 189,
            remaining_amount_net = 189,
            remaining_amount_vat = 0,
            remaining_foreign_amount_gross = 189,
            remaining_local_amount_gross = 10,
            salesperson_code = "FREESALE",
            positions = [position]
        ) # AccountingDocument | 

        document_id = 'document_id'
        try:
            # InsertPayment
            api_response = api_instance.accountingdocuments_document_id_put(body, document_id)
            # api_response = api_instance.accountingdocuments_document_id_put_with_http_info(body, None)
            pprint(api_response)
        except ApiException as e:
            print("Exception when calling DefaultApi->accounting_document: %s\n" % e)
            assert(False)

if __name__ == '__main__':
    unittest.main()
