Resources:
  secretdbcreds24C4962E:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: MappingDBPostgreSQL Credentials
      GenerateSecretString:
        ExcludePunctuation: true
        GenerateStringKey: password
        SecretStringTemplate: '{"username": "ifm"}'
      Name: ifm/db_creds
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: PostgreSqlStack/secret_db_creds/Resource
  vpcifm6FBA0E85:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.5.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: PostgreSqlStack/vpc_ifm
    Metadata:
      aws:cdk:path: PostgreSqlStack/vpc_ifm/Resource
  vpcifmPublicSubnet1SubnetA7366425:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-central-1c
      CidrBlock: 10.5.0.0/26
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: Public
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Name
          Value: PostgreSqlStack/vpc_ifm/PublicSubnet1
      VpcId:
        Ref: vpcifm6FBA0E85
    Metadata:
      aws:cdk:path: PostgreSqlStack/vpc_ifm/PublicSubnet1/Subnet
  vpcifmPublicSubnet1RouteTable5AA800A5:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: PostgreSqlStack/vpc_ifm/PublicSubnet1
      VpcId:
        Ref: vpcifm6FBA0E85
    Metadata:
      aws:cdk:path: PostgreSqlStack/vpc_ifm/PublicSubnet1/RouteTable
  vpcifmPublicSubnet1RouteTableAssociation3C6CD98D:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: vpcifmPublicSubnet1RouteTable5AA800A5
      SubnetId:
        Ref: vpcifmPublicSubnet1SubnetA7366425
    Metadata:
      aws:cdk:path: PostgreSqlStack/vpc_ifm/PublicSubnet1/RouteTableAssociation
  vpcifmPublicSubnet1DefaultRoute5BE79BAC:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: vpcifmIGWA19881DB
      RouteTableId:
        Ref: vpcifmPublicSubnet1RouteTable5AA800A5
    DependsOn:
      - vpcifmVPCGWE6C16550
    Metadata:
      aws:cdk:path: PostgreSqlStack/vpc_ifm/PublicSubnet1/DefaultRoute
  vpcifmPublicSubnet1EIP49835642:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: PostgreSqlStack/vpc_ifm/PublicSubnet1
    Metadata:
      aws:cdk:path: PostgreSqlStack/vpc_ifm/PublicSubnet1/EIP
  vpcifmPublicSubnet1NATGateway71EECF72:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - vpcifmPublicSubnet1EIP49835642
          - AllocationId
      SubnetId:
        Ref: vpcifmPublicSubnet1SubnetA7366425
      Tags:
        - Key: Name
          Value: PostgreSqlStack/vpc_ifm/PublicSubnet1
    DependsOn:
      - vpcifmPublicSubnet1DefaultRoute5BE79BAC
      - vpcifmPublicSubnet1RouteTableAssociation3C6CD98D
    Metadata:
      aws:cdk:path: PostgreSqlStack/vpc_ifm/PublicSubnet1/NATGateway
  vpcifmPrivateSubnet1SubnetDCCF273E:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-central-1c
      CidrBlock: 10.5.0.64/26
      MapPublicIpOnLaunch: false
      Tags:
        - Key: aws-cdk:subnet-name
          Value: Private
        - Key: aws-cdk:subnet-type
          Value: Private
        - Key: Name
          Value: PostgreSqlStack/vpc_ifm/PrivateSubnet1
      VpcId:
        Ref: vpcifm6FBA0E85
    Metadata:
      aws:cdk:path: PostgreSqlStack/vpc_ifm/PrivateSubnet1/Subnet
  vpcifmPrivateSubnet1RouteTable4EB62CF2:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: PostgreSqlStack/vpc_ifm/PrivateSubnet1
      VpcId:
        Ref: vpcifm6FBA0E85
    Metadata:
      aws:cdk:path: PostgreSqlStack/vpc_ifm/PrivateSubnet1/RouteTable
  vpcifmPrivateSubnet1RouteTableAssociation9FD843A1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: vpcifmPrivateSubnet1RouteTable4EB62CF2
      SubnetId:
        Ref: vpcifmPrivateSubnet1SubnetDCCF273E
    Metadata:
      aws:cdk:path: PostgreSqlStack/vpc_ifm/PrivateSubnet1/RouteTableAssociation
  vpcifmPrivateSubnet1DefaultRoute0E834390:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: vpcifmPublicSubnet1NATGateway71EECF72
      RouteTableId:
        Ref: vpcifmPrivateSubnet1RouteTable4EB62CF2
    Metadata:
      aws:cdk:path: PostgreSqlStack/vpc_ifm/PrivateSubnet1/DefaultRoute
  vpcifmIGWA19881DB:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: PostgreSqlStack/vpc_ifm
    Metadata:
      aws:cdk:path: PostgreSqlStack/vpc_ifm/IGW
  vpcifmVPCGWE6C16550:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: vpcifmIGWA19881DB
      VpcId:
        Ref: vpcifm6FBA0E85
    Metadata:
      aws:cdk:path: PostgreSqlStack/vpc_ifm/VPCGW
  vpcifmRestrictDefaultSecurityGroupCustomResource83E4342A:
    Type: Custom::VpcRestrictDefaultSG
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomVpcRestrictDefaultSGCustomResourceProviderHandlerDC833E5E
          - Arn
      DefaultSecurityGroupId:
        Fn::GetAtt:
          - vpcifm6FBA0E85
          - DefaultSecurityGroup
      Account:
        Ref: AWS::AccountId
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: PostgreSqlStack/vpc_ifm/RestrictDefaultSecurityGroupCustomResource/Default
  CustomVpcRestrictDefaultSGCustomResourceProviderRole26592FE0:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: Inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupEgress
                Resource:
                  - Fn::Join:
                      - ""
                      - - "arn:"
                        - Ref: AWS::Partition
                        - ":ec2:"
                        - Ref: AWS::Region
                        - ":"
                        - Ref: AWS::AccountId
                        - :security-group/
                        - Fn::GetAtt:
                            - vpcifm6FBA0E85
                            - DefaultSecurityGroup
    Metadata:
      aws:cdk:path: PostgreSqlStack/Custom::VpcRestrictDefaultSGCustomResourceProvider/Role
  CustomVpcRestrictDefaultSGCustomResourceProviderHandlerDC833E5E:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 4b996a3e5a083d5c78c6f30a8571a94fb7ec557eecbe54dbc065faba0d9076e6.zip
      Timeout: 900
      MemorySize: 128
      Handler: __entrypoint__.handler
      Role:
        Fn::GetAtt:
          - CustomVpcRestrictDefaultSGCustomResourceProviderRole26592FE0
          - Arn
      Runtime: nodejs18.x
      Description: Lambda function for removing all inbound/outbound rules from the VPC default security group
    DependsOn:
      - CustomVpcRestrictDefaultSGCustomResourceProviderRole26592FE0
    Metadata:
      aws:cdk:path: PostgreSqlStack/Custom::VpcRestrictDefaultSGCustomResourceProvider/Handler
      aws:asset:path: asset.4b996a3e5a083d5c78c6f30a8571a94fb7ec557eecbe54dbc065faba0d9076e6
      aws:asset:property: Code
  securitygroupifmdb04D5D63F:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: PostgreSqlStack/security_group_ifm_db
      GroupName: security_group_ifm_db
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp:
            Fn::GetAtt:
              - vpcifm6FBA0E85
              - CidrBlock
          Description:
            Fn::Join:
              - ""
              - - "from "
                - Fn::GetAtt:
                    - vpcifm6FBA0E85
                    - CidrBlock
                - :5432
          FromPort: 5432
          IpProtocol: tcp
          ToPort: 5432
      VpcId:
        Ref: vpcifm6FBA0E85
    Metadata:
      aws:cdk:path: PostgreSqlStack/security_group_ifm_db/Resource
  roleenhancedmonitoring1A8C293B:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
      RoleName: rds_enhanced_monitoring
    Metadata:
      aws:cdk:path: PostgreSqlStack/role_enhanced_monitoring/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/21QQW7CMBB8C3fjQjj1iKIKcamsUHGtNs42bIltZK9BUZS/125SculpZmfH9owL+bqTmxU8wlo313VHtRxODPoqkvQ5BNQeORiw0KJPq99ZlF92YqNAXcjhfNNZO6tSqFh3pE+xtrPvySoXGT+g7nDRF20fgtMETM4+zZm8HVWGd+ADMD6gF8rTPdHl4qNl9In/GaYk87Tn1OZi0LJIkaMn7g/exdvcYRFGQWDkULkpX8ZR+CZIBR4MpidmW4XBRa+TKwZ2ZhnTof9Xyrs7NehFKomcvrcl22Z/6WxDufIoVM8XZ192cruR22L1HYjWPlomg7Ka8Ad7h5j4rAEAAA==
    Metadata:
      aws:cdk:path: PostgreSqlStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

