# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ModifyInvoiceV3(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'modify_invoice_v3': 'AllOfModifyInvoiceV3ModifyInvoiceV3'
    }

    attribute_map = {
        'modify_invoice_v3': 'ModifyInvoiceV3'
    }

    def __init__(self, modify_invoice_v3=None):  # noqa: E501
        """ModifyInvoiceV3 - a model defined in Swagger"""  # noqa: E501
        self._modify_invoice_v3 = None
        self.discriminator = None
        self.modify_invoice_v3 = modify_invoice_v3

    @property
    def modify_invoice_v3(self):
        """Gets the modify_invoice_v3 of this ModifyInvoiceV3.  # noqa: E501


        :return: The modify_invoice_v3 of this ModifyInvoiceV3.  # noqa: E501
        :rtype: AllOfModifyInvoiceV3ModifyInvoiceV3
        """
        return self._modify_invoice_v3

    @modify_invoice_v3.setter
    def modify_invoice_v3(self, modify_invoice_v3):
        """Sets the modify_invoice_v3 of this ModifyInvoiceV3.


        :param modify_invoice_v3: The modify_invoice_v3 of this ModifyInvoiceV3.  # noqa: E501
        :type: AllOfModifyInvoiceV3ModifyInvoiceV3
        """
        # TBD: Investigate why None is not OK here
        # if modify_invoice_v3 is None:
        #     raise ValueError("Invalid value for `modify_invoice_v3`, must not be `None`")  # noqa: E501

        self._modify_invoice_v3 = modify_invoice_v3

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModifyInvoiceV3, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModifyInvoiceV3):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
