# coding: utf-8

"""
    HPP-V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.q30_document import Q30Document  # noqa: E501
from ods_client.rest import ApiException


class TestQ30Document(unittest.TestCase):
    """Q30Document unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQ30Document(self):
        """Test Q30Document"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.q30_document.Q30Document()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
