# coding: utf-8

"""
    HPP-V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.all_oftns_change_customer_address_v2_customer_address import AllOftnsChangeCustomerAddressV2CustomerAddress  # noqa: E501
from ods_client.rest import ApiException


class TestAllOftnsChangeCustomerAddressV2CustomerAddress(unittest.TestCase):
    """AllOftnsChangeCustomerAddressV2CustomerAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOftnsChangeCustomerAddressV2CustomerAddress(self):
        """Test AllOftnsChangeCustomerAddressV2CustomerAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_oftns_change_customer_address_v2_customer_address.AllOftnsChangeCustomerAddressV2CustomerAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
