# coding: utf-8

"""
    HPP-V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.all_of_modify_invoice_v3_modify_invoice_v3 import AllOfModifyInvoiceV3ModifyInvoiceV3  # noqa: E501
from ods_client.rest import ApiException


class TestAllOfModifyInvoiceV3ModifyInvoiceV3(unittest.TestCase):
    """AllOfModifyInvoiceV3ModifyInvoiceV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfModifyInvoiceV3ModifyInvoiceV3(self):
        """Test AllOfModifyInvoiceV3ModifyInvoiceV3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_modify_invoice_v3_modify_invoice_v3.AllOfModifyInvoiceV3ModifyInvoiceV3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
