# coding: utf-8

"""
    HPP-V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.all_oftns_change_invoice_address_invoice_address import AllOftnsChangeInvoiceAddressInvoiceAddress  # noqa: E501
from ods_client.rest import ApiException


class TestAllOftnsChangeInvoiceAddressInvoiceAddress(unittest.TestCase):
    """AllOftnsChangeInvoiceAddressInvoiceAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOftnsChangeInvoiceAddressInvoiceAddress(self):
        """Test AllOftnsChangeInvoiceAddressInvoiceAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_oftns_change_invoice_address_invoice_address.AllOftnsChangeInvoiceAddressInvoiceAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
