# coding: utf-8

"""
    HPP-V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.q10_invoice_address import Q10InvoiceAddress  # noqa: E501
from ods_client.rest import ApiException


class TestQ10InvoiceAddress(unittest.TestCase):
    """Q10InvoiceAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQ10InvoiceAddress(self):
        """Test Q10InvoiceAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.q10_invoice_address.Q10InvoiceAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
