# coding: utf-8

"""
    HPP-V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.tns_modify_invoice_v2 import TnsModifyInvoiceV2  # noqa: E501
from ods_client.rest import ApiException


class TestTnsModifyInvoiceV2(unittest.TestCase):
    """TnsModifyInvoiceV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTnsModifyInvoiceV2(self):
        """Test TnsModifyInvoiceV2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tns_modify_invoice_v2.TnsModifyInvoiceV2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
