# coding: utf-8

"""
    HPP-V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.all_of_confirm_invoice_confirm_invoice import AllOfConfirmInvoiceConfirmInvoice  # noqa: E501
from ods_client.rest import ApiException


class TestAllOfConfirmInvoiceConfirmInvoice(unittest.TestCase):
    """AllOfConfirmInvoiceConfirmInvoice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfConfirmInvoiceConfirmInvoice(self):
        """Test AllOfConfirmInvoiceConfirmInvoice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_confirm_invoice_confirm_invoice.AllOfConfirmInvoiceConfirmInvoice()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
