# coding: utf-8

"""
    HPP-V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ods_client
from ods_client.models.q2_invoices import Q2Invoices  # noqa: E501
from ods_client.rest import ApiException


class TestQ2Invoices(unittest.TestCase):
    """Q2Invoices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQ2Invoices(self):
        """Test Q2Invoices"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.q2_invoices.Q2Invoices()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
