# coding: utf-8

"""
    HPP-V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Q30Document(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'reservation_no': 'str',
        'payment_amount': 'str'
    }

    attribute_map = {
        'reservation_no': 'ReservationNo',
        'payment_amount': 'PaymentAmount'
    }

    def __init__(self, reservation_no=None, payment_amount=None):  # noqa: E501
        """Q30Document - a model defined in Swagger"""  # noqa: E501
        self._reservation_no = None
        self._payment_amount = None
        self.discriminator = None
        self.reservation_no = reservation_no
        self.payment_amount = payment_amount

    @property
    def reservation_no(self):
        """Gets the reservation_no of this Q30Document.  # noqa: E501


        :return: The reservation_no of this Q30Document.  # noqa: E501
        :rtype: str
        """
        return self._reservation_no

    @reservation_no.setter
    def reservation_no(self, reservation_no):
        """Sets the reservation_no of this Q30Document.


        :param reservation_no: The reservation_no of this Q30Document.  # noqa: E501
        :type: str
        """
        if reservation_no is None:
            raise ValueError("Invalid value for `reservation_no`, must not be `None`")  # noqa: E501

        self._reservation_no = reservation_no

    @property
    def payment_amount(self):
        """Gets the payment_amount of this Q30Document.  # noqa: E501


        :return: The payment_amount of this Q30Document.  # noqa: E501
        :rtype: str
        """
        return self._payment_amount

    @payment_amount.setter
    def payment_amount(self, payment_amount):
        """Sets the payment_amount of this Q30Document.


        :param payment_amount: The payment_amount of this Q30Document.  # noqa: E501
        :type: str
        """
        if payment_amount is None:
            raise ValueError("Invalid value for `payment_amount`, must not be `None`")  # noqa: E501

        self._payment_amount = payment_amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Q30Document, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Q30Document):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
