# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tns_insert_payment_v3 import TnsInsertPaymentV3  # noqa: E501
from swagger_client.rest import ApiException


class TestTnsInsertPaymentV3(unittest.TestCase):
    """TnsInsertPaymentV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTnsInsertPaymentV3(self):
        """Test TnsInsertPaymentV3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tns_insert_payment_v3.TnsInsertPaymentV3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
