# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_oftns_insert_payment_v3_insert_payment import AllOftnsInsertPaymentV3InsertPayment  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOftnsInsertPaymentV3InsertPayment(unittest.TestCase):
    """AllOftnsInsertPaymentV3InsertPayment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOftnsInsertPaymentV3InsertPayment(self):
        """Test AllOftnsInsertPaymentV3InsertPayment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_oftns_insert_payment_v3_insert_payment.AllOftnsInsertPaymentV3InsertPayment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
