# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.q22_positions import Q22Positions  # noqa: E501
from swagger_client.rest import ApiException


class TestQ22Positions(unittest.TestCase):
    """Q22Positions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQ22Positions(self):
        """Test Q22Positions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.q22_positions.Q22Positions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
