# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.q12_documents import Q12Documents  # noqa: E501
from swagger_client.rest import ApiException


class TestQ12Documents(unittest.TestCase):
    """Q12Documents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQ12Documents(self):
        """Test Q12Documents"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.q12_documents.Q12Documents()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
