# coding: utf-8

"""
    HPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_insert_payment_v3_insert_payment_v3 import AllOfInsertPaymentV3InsertPaymentV3  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfInsertPaymentV3InsertPaymentV3(unittest.TestCase):
    """AllOfInsertPaymentV3InsertPaymentV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfInsertPaymentV3InsertPaymentV3(self):
        """Test AllOfInsertPaymentV3InsertPaymentV3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_insert_payment_v3_insert_payment_v3.AllOfInsertPaymentV3InsertPaymentV3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
