openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Marquardt-Informatik/dataMigration/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Marquardt-Informatik/comGenJournalPostAPI/1.0.0
info:
  version: "1.0.0"
  title: Complemedis dataMigration API
  contact:
    email: you@your-company.com
components:
    schemas:
      comGenJournalPostAPI:
        type: object
        properties:
          id:
            type: integer
            format: int64
    Schema:
      type: object
      properties:
        id:
          type: integer
          format: int64
