swagger: '2.0'
info:
  description: this API lets BC create a license
  version: 1.0.2
  title: Create or Modify BC License
  # put the contact info for your development or API team
  contact:
    email: info@marquardt-informatik.koeln

# tags are used for organizing operations
tags:
- name: developers
  description: Operations available to regular developers
paths:
  /license:
    post:
      summary: adds a license entry in bc
      operationId: addLicense
      description: Adds a license to the system
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: license
        description: License to add
        schema:
          $ref: '#/definitions/License'
      responses:
        200:
          description: Created License
          schema:
            $ref: '#/definitions/LicenseResult'
      tags:
        - developers
definitions:
  License:
    type: object
    required:
    - licenseId
    - opportunityProductId
    - courseId
    - studentId
    - quantity
    - sessionStatus
    properties:
      licenseId:
        type: number
        format: int32
        example: 132934
        description: Unique License ID
      dateOfService:
        type: string
        format: date
        example: 07/07/2021
        description: Date of license usage   
      accountItemId:
        type: string
        example: 132934
        description: Account ID
      opportunityProductId:
        type: string
        example: 0012000000ZRUqYAAX
        description: Unique Sforce Opportunity Product ID
      courseId:
        type: string
        example: 12345
        description: Unique Course ID
      studentId:
        type: string
        example: abcdfg
        description: Unique Student ID  
      quantity:
        type: number
        format: double
        example: 1
        minimum: 1
        description: Original quantity as pool entry was created
      sessionLength:
        type: number
        format: double
        example: 60
        minimum: 1
        description: Length of Session
      attendeeStatus:
        type: string
        example: participated
        description: Status of attendee
      sessionStatus:
        type: string
        example: finished
        description: Status of attendee  
      cancelationReason:
        type: string
        example: 
        description: Reason as if the license was canceled
      attendeeRole:
        type: string
        enum: [student,trainer]
        example: student
        description: Assigned to Trainer or Student
  LicenseResult:
    type: object
    required:
    - '@odata.etag'
    properties:
      '@odata.etag':
        type: string
        example: W/\"JzQ0O1NXRXlNZ0c0SndFS2tYcmFEMm5jbHVZeEVGNWNnQlI1RklkcG0xcGhkaUU9MTswMDsn\"
      licenseId:
        type: number
        format: int32
        example: 132934
        description: Unique License ID
      dateOfService:
        type: string
        format: date
        example: 07/07/2021
        description: Date of license usage   
      accountItemId:
        type: string
        example: 132934
        description: Account ID
      opportunityProductId:
        type: string
        example: 0012000000ZRUqYAAX
        description: Unique Sforce Opportunity Product ID
      courseId:
        type: string
        example: 12345
        description: Unique Course ID
      studentId:
        type: string
        example: abcdfg
        description: Unique Student ID  
      quantity:
        type: number
        format: double
        example: 1
        minimum: 1
        description: Original quantity as pool entry was created
      sessionLength:
        type: number
        format: double
        example: 60
        minimum: 1
        description: Length of Session
      attendeeStatus:
        type: string
        example: participated
        description: Status of attendee
      sessionStatus:
        type: string
        example: participated
        description: Status of attendee  
      cancelationReason:
        type: string
        example: 
        description: Reason as if the license was canceled 
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
schemes:
 - https
# Added by API Auto Mocking Plugin
basePath: /Marquardt-Informatik/license/1.0.2
