swagger: '2.0'
info:
  description: this API lets NAV create or modify a Customer
  version: 1.0.0.0
  title: Create or modify NAV Customer
  # put the contact info for your development or API team
  contact:
    email: info@marquardt-informatik.koeln

# tags are used for organizing operations
tags:
- name: developers
  description: Operations available to regular developers
paths:
  /partnerCreated:
    post:
      tags:
      - developers
      operationId: createPartner
      description: Adds a customer to NAV
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: partner
        description: Customer to add
        schema:
          $ref: '#/definitions/PartnerCreated'
      responses:
        200:
          description: Created Customer
          schema:
            $ref: '#/definitions/PartnerCreatedResult'
  /partnerUpdated:
    post:
      tags:
      - developers
      operationId: updatePartner
      description: Update a customer in NAV
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: partner
        description: Customer to update
        schema:
          $ref: '#/definitions/PartnerUpdated'
      responses:
        200:
          description: Updated Customer
          schema:
            $ref: '#/definitions/PartnerUpdatedResult'
definitions:
  PartnerCreated:
    type: object
    required:
    - newWorkPartnerId
    - addressInformation
    - vatId
    properties:
      newWorkPartnerId:
        type: string
        example: 00004b3b-3730-b07c-b433-d26d876ff5b3
      addressInformation:
        type: object
        $ref: '#/definitions/Address'
      bankInformation:
        type: object
        $ref: '#/definitions/BankInformation'
      correspondenceInformation:
        type: object
        $ref: '#/definitions/CorrespondenceInformation'
      vatId:
        type: string
        example: DE12345678
        description: VAT Registration No.
  PartnerCreatedResult:
    type: object
    required:
    - newWorkPartnerId
    - navCustomerNo
    properties:
      newWorkPartnerId:
        type: string
        example: 00004b3b-3730-b07c-b433-d26d876ff5b3
      navCustomerNo:
        type: string
        example: 60010345
  PartnerUpdated:
    type: object
    required:
    - newWorkPartnerId
    - addressInformation
    - vatId
    properties:
      newWorkPartnerId:
        type: string
        example: 00004b3b-3730-b07c-b433-d26d876ff5b3
      addressInformation:
        type: object
        $ref: '#/definitions/Address'
      bankInformation:
        type: object
        $ref: '#/definitions/BankInformation'
      correspondenceInformation:
        type: object
        $ref: '#/definitions/CorrespondenceInformation'
      vatId:
        type: string
        example: DE12345678
        description: VAT Registration No.
  PartnerUpdatedResult:
    type: object
    required:
    - newWorkPartnerId
    - navCustomerNo
    properties:
      newWorkPartnerId:
        type: string
        example: 00004b3b-3730-b07c-b433-d26d876ff5b3
      navCustomerNo:
        type: string
        example: 60010345
  Address:
    type: object
    required:
    - name
    - street
    - postCode
    - city
    - country
    properties:
      name:
        type: string
        example: Savoy Hotel
      name2:
        type: string
        example: Berlin GmbH & Co KG
      street:
        type: string
        example: Fasanenstrasse 9-10
      street2:
        type: string
      postCode:
        type: string
        example: 10623
      city:
        type: string
        example: Berlin
  BankInformation:
    type: object
    properties:
      bankName:
        type: string
        example: BERLINER SPARKASSE - LANDESBANK BERLIN AG
      swiftCode:
        type: string
        example: BELADEBEXXX
      iban:
        type: string
        example: DE56100500000190275022
      bankNumber:
        type: string
      bankAccountNumber:
        type: string
      transitNumber:
        type: string
        description: used for international bank transfer
      mandateId:
        type: string
      mandateType:
        type: string
        enum: [RCUR,SNGL]
        description: RCUR recuring, SNGL single=onetime
  CorrespondenceInformation:
    type: object
    properties:
      eMail: 
        type: string
        example: reservierung@hotel-savoy.com
      homePage:
        type: string
        example: www.hotel-savoy.com
      phoneNumber:
        type: string
        example: 030311030
      contactPerson:
        type: string
        example: Ute Ahrens
      
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
schemes:
 - https
# Added by API Auto Mocking Plugin
basePath: /Marquardt-Informatik/partner/1.0.0.1
